
enum app_states {
	UNINITIALIZED = 1,
	INITFAILED,
	INITIALIZED,
	RUN_PREFS,
	RUNNING_PREFS,
	SCAN_JOB_BARCODE,
	PICK_MODEL,
	PICK_PERSON,
	SCAN_BAG_BARCODE,
	CAMERA_CAPTURE,
	PICK_COLOR,
	PICK_STYLE,
	SCAN_ACTION_PARAM_BARCODE,
	CREATE_JOB,
	SUBMIT_BAG,
	SUBMIT_ACTION_TYPE0,
	SUBMIT_ACTION_TYPE1,
	SUBMIT_JOB_FAILED,
	SUBMIT_BAG_FAILED,
	SUBMIT_ACTION_FAILED,
	CONFIRM_ACTION_SUCCESS,
};



