
enum app_states {
	UNINITIALIZED = 1,
	INITFAILED,
	INITIALIZED,
	RUN_PREFS,
	RUNNING_PREFS,
	SCAN_JOB_BARCODE,
	PICK_MODEL,
	PICK_PERSON,
	SCAN_BAG_BARCODE,
	CAMERA_CAPTURE,
	PICK_COLOR,
	PICK_COLOR2,
	PICK_STYLE,
	PICK_QUALITY,
	ENTER_WEIGHT,
	SCAN_ACTION_PARAM_BARCODE,
	CREATE_JOB,
	SUBMIT_BAG,
	SUBMIT_ACTION_TYPE0,
	SUBMIT_ACTION_TYPE1,
	SUBMIT_JOB_FAILED,
	SUBMIT_BAG_FAILED,
	SUBMIT_TARP_FAILED,
	SUBMIT_ACTION_FAILED,
	SUBMIT_TARP,
	CONFIRM_ACTION_SUCCESS,
	
	SCAN_TARP_BARCODE
};

enum client_modes {
	CLIENT_MODE_BAG = 0,
	CLIENT_MODE_TARP = 1
};

